// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientRequestType struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequestType) Reset()         { *m = ClientRequestType{} }
func (m *ClientRequestType) String() string { return proto.CompactTextString(m) }
func (*ClientRequestType) ProtoMessage()    {}
func (*ClientRequestType) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *ClientRequestType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequestType.Unmarshal(m, b)
}
func (m *ClientRequestType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequestType.Marshal(b, m, deterministic)
}
func (m *ClientRequestType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequestType.Merge(m, src)
}
func (m *ClientRequestType) XXX_Size() int {
	return xxx_messageInfo_ClientRequestType.Size(m)
}
func (m *ClientRequestType) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequestType.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequestType proto.InternalMessageInfo

func (m *ClientRequestType) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

type ClientResponseType struct {
	ProductType          string   `protobuf:"bytes,1,opt,name=productType,proto3" json:"productType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientResponseType) Reset()         { *m = ClientResponseType{} }
func (m *ClientResponseType) String() string { return proto.CompactTextString(m) }
func (*ClientResponseType) ProtoMessage()    {}
func (*ClientResponseType) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ClientResponseType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientResponseType.Unmarshal(m, b)
}
func (m *ClientResponseType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientResponseType.Marshal(b, m, deterministic)
}
func (m *ClientResponseType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientResponseType.Merge(m, src)
}
func (m *ClientResponseType) XXX_Size() int {
	return xxx_messageInfo_ClientResponseType.Size(m)
}
func (m *ClientResponseType) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientResponseType.DiscardUnknown(m)
}

var xxx_messageInfo_ClientResponseType proto.InternalMessageInfo

func (m *ClientResponseType) GetProductType() string {
	if m != nil {
		return m.ProductType
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientRequestType)(nil), "api.ClientRequestType")
	proto.RegisterType((*ClientResponseType)(nil), "api.ClientResponseType")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0xd2, 0xe6, 0x12, 0x74, 0xce,
	0xc9, 0x4c, 0xcd, 0x2b, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x09, 0xa9, 0x2c, 0x48, 0x15,
	0x12, 0xe3, 0x62, 0x2b, 0x4b, 0xcd, 0x4b, 0xc9, 0x2f, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x82, 0xf2, 0x94, 0xcc, 0xb8, 0x84, 0x60, 0x8a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xc1, 0xaa,
	0x15, 0xb8, 0xb8, 0x0b, 0x8a, 0xf2, 0x53, 0x4a, 0x93, 0xc1, 0x9a, 0xa1, 0x5a, 0x90, 0x85, 0x8c,
	0x42, 0xb8, 0xb8, 0x03, 0x8a, 0xf2, 0x53, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x5c,
	0xb9, 0x84, 0xdc, 0x53, 0x4b, 0xc2, 0xc0, 0x66, 0x82, 0xc4, 0x41, 0x6a, 0x8a, 0x85, 0xc4, 0xf4,
	0x40, 0x4e, 0xc3, 0x70, 0x8c, 0x94, 0x38, 0x8a, 0x38, 0xc2, 0xde, 0x24, 0x36, 0xb0, 0x37, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x27, 0xc0, 0xf7, 0xd9, 0xd3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProdServiceClient is the client API for ProdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProdServiceClient interface {
	GetVendorProdTypes(ctx context.Context, in *ClientRequestType, opts ...grpc.CallOption) (*ClientResponseType, error)
}

type prodServiceClient struct {
	cc *grpc.ClientConn
}

func NewProdServiceClient(cc *grpc.ClientConn) ProdServiceClient {
	return &prodServiceClient{cc}
}

func (c *prodServiceClient) GetVendorProdTypes(ctx context.Context, in *ClientRequestType, opts ...grpc.CallOption) (*ClientResponseType, error) {
	out := new(ClientResponseType)
	err := c.cc.Invoke(ctx, "/api.ProdService/GetVendorProdTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProdServiceServer is the server API for ProdService service.
type ProdServiceServer interface {
	GetVendorProdTypes(context.Context, *ClientRequestType) (*ClientResponseType, error)
}

// UnimplementedProdServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProdServiceServer struct {
}

func (*UnimplementedProdServiceServer) GetVendorProdTypes(ctx context.Context, req *ClientRequestType) (*ClientResponseType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVendorProdTypes not implemented")
}

func RegisterProdServiceServer(s *grpc.Server, srv ProdServiceServer) {
	s.RegisterService(&_ProdService_serviceDesc, srv)
}

func _ProdService_GetVendorProdTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequestType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProdServiceServer).GetVendorProdTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ProdService/GetVendorProdTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProdServiceServer).GetVendorProdTypes(ctx, req.(*ClientRequestType))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProdService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ProdService",
	HandlerType: (*ProdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVendorProdTypes",
			Handler:    _ProdService_GetVendorProdTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
