# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tapi.proto\x12\x03\x61pi\x1a\x1cgoogle/api/annotations.proto\"#\n\x11\x43lientRequestType\x12\x0e\n\x06vendor\x18\x01 \x01(\t\")\n\x12\x43lientResponseType\x12\x13\n\x0bproductType\x18\x01 \x01(\t\"9\n\x12\x43lientRequestProds\x12\x0e\n\x06vendor\x18\x01 \x01(\t\x12\x13\n\x0bproductType\x18\x02 \x01(\t\"6\n\x13\x43lientResponseProds\x12\x1f\n\x07product\x18\x01 \x01(\x0b\x32\x0e.api.ProdsPrep\"9\n\tProdsPrep\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x10\n\x08shortUrl\x18\x03 \x01(\t\"5\n\x0eStorageRequest\x12\x0e\n\x06vendor\x18\x01 \x01(\t\x12\x13\n\x0bproductType\x18\x02 \x01(\t\"3\n\x0fStorageResponse\x12 \n\nprodDetail\x18\x01 \x03(\x0b\x32\x0c.api.Product\"%\n\x07Product\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t2\xc7\x01\n\x0bProdService\x12]\n\x12GetVendorProdTypes\x12\x16.api.ClientRequestType\x1a\x17.api.ClientResponseType\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/prodtypes\x12Y\n\x0eGetVendorProds\x12\x17.api.ClientRequestProds\x1a\x18.api.ClientResponseProds\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/api/prods0\x01\x32M\n\x0eStorageService\x12;\n\x0eGetProdsDetail\x12\x13.api.StorageRequest\x1a\x14.api.StorageResponseb\x06proto3')
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_CLIENTREQUESTTYPE = _descriptor.Descriptor(
  name='ClientRequestType',
  full_name='api.ClientRequestType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vendor', full_name='api.ClientRequestType.vendor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=83,
)


_CLIENTRESPONSETYPE = _descriptor.Descriptor(
  name='ClientResponseType',
  full_name='api.ClientResponseType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='productType', full_name='api.ClientResponseType.productType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=126,
)


_CLIENTREQUESTPRODS = _descriptor.Descriptor(
  name='ClientRequestProds',
  full_name='api.ClientRequestProds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vendor', full_name='api.ClientRequestProds.vendor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productType', full_name='api.ClientRequestProds.productType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=185,
)


_CLIENTRESPONSEPRODS = _descriptor.Descriptor(
  name='ClientResponseProds',
  full_name='api.ClientResponseProds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product', full_name='api.ClientResponseProds.product', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=241,
)


_PRODSPREP = _descriptor.Descriptor(
  name='ProdsPrep',
  full_name='api.ProdsPrep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='api.ProdsPrep.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='api.ProdsPrep.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shortUrl', full_name='api.ProdsPrep.shortUrl', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=300,
)


_STORAGEREQUEST = _descriptor.Descriptor(
  name='StorageRequest',
  full_name='api.StorageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vendor', full_name='api.StorageRequest.vendor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='productType', full_name='api.StorageRequest.productType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=355,
)


_STORAGERESPONSE = _descriptor.Descriptor(
  name='StorageResponse',
  full_name='api.StorageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prodDetail', full_name='api.StorageResponse.prodDetail', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=357,
  serialized_end=408,
)


_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='api.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='api.Product.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='api.Product.url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=447,
)

_CLIENTRESPONSEPRODS.fields_by_name['product'].message_type = _PRODSPREP
_STORAGERESPONSE.fields_by_name['prodDetail'].message_type = _PRODUCT
DESCRIPTOR.message_types_by_name['ClientRequestType'] = _CLIENTREQUESTTYPE
DESCRIPTOR.message_types_by_name['ClientResponseType'] = _CLIENTRESPONSETYPE
DESCRIPTOR.message_types_by_name['ClientRequestProds'] = _CLIENTREQUESTPRODS
DESCRIPTOR.message_types_by_name['ClientResponseProds'] = _CLIENTRESPONSEPRODS
DESCRIPTOR.message_types_by_name['ProdsPrep'] = _PRODSPREP
DESCRIPTOR.message_types_by_name['StorageRequest'] = _STORAGEREQUEST
DESCRIPTOR.message_types_by_name['StorageResponse'] = _STORAGERESPONSE
DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientRequestType = _reflection.GeneratedProtocolMessageType('ClientRequestType', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUESTTYPE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ClientRequestType)
  })
_sym_db.RegisterMessage(ClientRequestType)

ClientResponseType = _reflection.GeneratedProtocolMessageType('ClientResponseType', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRESPONSETYPE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ClientResponseType)
  })
_sym_db.RegisterMessage(ClientResponseType)

ClientRequestProds = _reflection.GeneratedProtocolMessageType('ClientRequestProds', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREQUESTPRODS,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ClientRequestProds)
  })
_sym_db.RegisterMessage(ClientRequestProds)

ClientResponseProds = _reflection.GeneratedProtocolMessageType('ClientResponseProds', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTRESPONSEPRODS,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ClientResponseProds)
  })
_sym_db.RegisterMessage(ClientResponseProds)

ProdsPrep = _reflection.GeneratedProtocolMessageType('ProdsPrep', (_message.Message,), {
  'DESCRIPTOR' : _PRODSPREP,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.ProdsPrep)
  })
_sym_db.RegisterMessage(ProdsPrep)

StorageRequest = _reflection.GeneratedProtocolMessageType('StorageRequest', (_message.Message,), {
  'DESCRIPTOR' : _STORAGEREQUEST,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.StorageRequest)
  })
_sym_db.RegisterMessage(StorageRequest)

StorageResponse = _reflection.GeneratedProtocolMessageType('StorageResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORAGERESPONSE,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.StorageResponse)
  })
_sym_db.RegisterMessage(StorageResponse)

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCT,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:api.Product)
  })
_sym_db.RegisterMessage(Product)



_PRODSERVICE = _descriptor.ServiceDescriptor(
  name='ProdService',
  full_name='api.ProdService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=450,
  serialized_end=649,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetVendorProdTypes',
    full_name='api.ProdService.GetVendorProdTypes',
    index=0,
    containing_service=None,
    input_type=_CLIENTREQUESTTYPE,
    output_type=_CLIENTRESPONSETYPE,
    serialized_options=_b('\202\323\344\223\002\020\022\016/api/prodtypes'),
  ),
  _descriptor.MethodDescriptor(
    name='GetVendorProds',
    full_name='api.ProdService.GetVendorProds',
    index=1,
    containing_service=None,
    input_type=_CLIENTREQUESTPRODS,
    output_type=_CLIENTRESPONSEPRODS,
    serialized_options=_b('\202\323\344\223\002\014\022\n/api/prods'),
  ),
])
_sym_db.RegisterServiceDescriptor(_PRODSERVICE)

DESCRIPTOR.services_by_name['ProdService'] = _PRODSERVICE


_STORAGESERVICE = _descriptor.ServiceDescriptor(
  name='StorageService',
  full_name='api.StorageService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=651,
  serialized_end=728,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProdsDetail',
    full_name='api.StorageService.GetProdsDetail',
    index=0,
    containing_service=None,
    input_type=_STORAGEREQUEST,
    output_type=_STORAGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STORAGESERVICE)

DESCRIPTOR.services_by_name['StorageService'] = _STORAGESERVICE

# @@protoc_insertion_point(module_scope)
